### ISSUE TITLE
rate.php is not valid anymore

### ISSUE THREAD

**Issue by lg2de** [abc874/ca2018#2]
The URL to rate a cutlist is not valid anymore: `cutlist.at/rate.php` is not accepted.
I'm not sure what is the right (new) URL...

The URL is hard coded in `Main.pas`.

Is there an instruction build the source code?
Then maybe I would be able to contribute the required change?

**Comment by abc874** [comment]
Sorry, missed that post. I am rarely here.

But ... rating still works.

See http://cutlist.at/#!/faq for instructions.

<hr>

How to build:

- Read "readme.txt" files in subdirs "KDL" and "DSPack"
- Download both components sources
- Patch DSPack
- Install DSPack-package.
- Open "cut_assistant.dpr" and compile
