### ISSUE TITLE
Open cutlist filename misses extension

### ISSUE THREAD

**Issue by BastianKanaan** [abc874/ca2018#3]
The suggested filename to open a saved cutlist misses the extension of the video file.
For example the video "some_video.HQ.avi" would belong to a cutlist "some_video.HQ.avi.cutlist". The "Load Cut List" dialog offers the name ""some_video.HQ.cutlist".

**Steps to reproduce the behavior:**
1. Load a video.
2. Click on 'Open Cutlist...' (Menu Cutlist),
3. See file name.

**Expected behavior:**
File name of video with extension + ".cutlist"

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by abc874** [comment]
See release 0.20.11.18


Missed this post. Issue notification not working?
Changed some settings, hope next time I got notification mail.
