### ISSUE TITLE
The text box under Cutlist Info in the "Suggested movie file name (without extension)" field is no longer used as the file name for the cut file. 

### ISSUE THREAD

**Issue by kielbasam** [abc874/ca2018#4]
**Describe the bug**

In the menu -> Cutlist -> Cutlist Info, in the text field: "Suggested film file name (without extension)",

the text field is no longer accepted as the file name for the cutting file.

This was very useful because you could use the filename of the original file without underscores.
Instead, just a ".cut" with the name of the original file is placed in front of the file extension.

Thank you for continuing the project. 

**Screenshots**
![image](https://user-images.githubusercontent.com/29279043/127920272-043e3247-7c6f-4086-a9d1-402941cf4a29.png)

**Desktop (please complete the following information):**
 - Windows 10 Pro
 - 20H2

** Software Version:
Cut Assistant, Version: 0.21.4.4

**Comment by abc874** [comment]
There was no change. Works still as expected. Same as in version 0.9.13.16 

Example, loaded file: FBI__Most_Wanted_21.08.05_23-15_sat1_50_TVOON_DE.mpg.mp4

Case A
Field "Sugg. name" empty -> Save as FBI__Most_Wanted_21.08.05_23-15_sat1_50_TVOON_DE.mpg.cut.mp4

Case B
Field "Sugg. name" contains "foo" -> Save as foo.mp4

Case C
Field "Sugg. name" contains "foo_bar" -> Save as foo_bar.mp4


Please also check Options -> Save movie and Options -> Replace filename.

**Comment by abc874** [comment]
No response and no change needed.
